# Generated by Django 4.2.7 on 2023-11-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notekeeper', '0002_alter_notekeeper_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notekeeper',
            name='description',
            field=models.TextField(blank=True, default='Some text', max_length=300, null=True),
        ),
    ]
